### ISSUE TITLE
Doesn't appear to support "AS" aliases

### ISSUE THREAD

**Issue by lee-dohm** [DavidLGoldberg/qolor#10]
Perhaps I'm using archaic syntax, but I noticed that aliases after `AS` are not recognized:

``` sql
SELECT c.name AS name, a.street_address AS street1
  FROM customer AS c
  JOIN address AS a
 WHERE c.id = a.customer_id
```

**Comment by DavidLGoldberg** [comment]
Oops! Thanks Lee! I was just telling someone how frustratingly flexible sql is haha.

My other friend has a funny story where a boss was arguing with him that the sql wouldn't run without the 'as'.

I'll get on this one :)
