### ISSUE TITLE
Handle CTEs

### ISSUE THREAD

**Issue by jeremytwfortune** [DavidLGoldberg/qolor#17]
Syntax that looks like this:

``` sql
with tbl1 as (
  ...
), tbl2 as (
  ...
)
select * from tbl1;
```

Currently only highlights the `tbl1` reference in the `from` clause. It would be great to also highlight the `with` sections!

**Comment by DavidLGoldberg** [comment]
Yup, been coming up in my stuff too...

How do you like the package?  Helpful at all?  Does it mostly work for your queries, or all broken?  (mostly works / is helpful at my job)

I'll _try_ to get some time to put another round of additions, with this and cross apply, few things.

The code is definitely nutty though :)

**Comment by jeremytwfortune** [comment]
I think it's a fantastic idea. It's especially good when having to read wacky aliases from 400 lines down in the script. I have a few on my team that like to use enumerated aliases, ("A", "B", etc.). 

Considering I make heavy use of CTEs, this issue definitely shows up a lot. But overall, when it works, it's a fantastic addition that saves me that extra scroll back down to the `from`.

**Comment by DavidLGoldberg** [comment]
Thanks, yeah I'll definitely give CTEs a go this weekend.

**Comment by DavidLGoldberg** [comment]
@jeremytwfortune Would you mind weighing in on #12 ?  Also, What RDBMS do you use?

**Comment by jeremytwfortune** [comment]
Sure, I'll head over there. I primarily use SQL Server and IBM PureData.
