### ISSUE TITLE
Failed to activate the qolor package

### ISSUE THREAD

**Issue by GiTLeR69** [DavidLGoldberg/qolor#28]
[Enter steps to reproduce:]

1. start Atom by clicking icon pinned to dock

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [qolor](https://github.com/davidlgoldberg/qolor) package 0.4.2

### Stack Trace

Failed to activate the qolor package

```
At unexpected � in /Users/USERNAME/.atom/packages/qolor/lib/qolor.coffee:1:1

SyntaxError: unexpected �
  at /packages/qolor/lib/qolor.coffee:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.2 
atom-clock 0.1.10 
autoclose-html 0.23.0 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.7 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-php 1.3.2 
linter-ui-default 1.6.1 
minimap 4.28.2 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
open-recent 5.0.0 
panic-palette 0.1.0 
php-twig 4.0.0 
pigments 0.39.1 
project-manager 3.3.5 
qolor 0.4.2 
rest-client 1.3.1 
seti-syntax 1.1.3 
seti-ui 1.8.0 
todo-show 1.11.0 
```

**Comment by DavidLGoldberg** [comment]
Thanks for submitting!

Hmm, I'm on the same exact mac and atom and don't see any issue.

Could you give me more insight into that character that's not coming in clear that looks like a '?' with a ruby around it.

Also, did you try restarting atom? Maybe try with ctrl+alt+cmd+l  (<--l as in Load....it reloads atom)

One more thought.  If you wouldn't mind experimenting do:
`apm disable php-twig panic-palette autocomplete-php linter-php`

I think I have everything else installed :)

don't forget to renenable:
`apm enable php-twig panic-palette autocomplete-php linter-php`

**Comment by DavidLGoldberg** [comment]
I haven't heard anything back so going to have to close it for now.
